
export type ActivityType = 
    | "story"
    | "multiChoiceQuiz"
    | "vocabReview"
    | "writeExtra"
    | "observe"
    | "observeDescribe"
    | "readModel"
    | "freeWriting"
    | "topicPrediction"
    | "research"
    | "textQuestionAnswer"
    | "writingScaffold"
    | "reflectionSurvey"